import { Inter } from 'next/font/google'
import NavBar from '@/components/navbar'

import './globals.css'

const inter = Inter({
    subsets: ['latin']
})

export const metadata = {
    title: 'Majestic Food',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <html lang="es">
            <body className={inter.className}>
                <main className="flex min-h-screen flex-col">
                    <NavBar />
                    <div className='space w-full h-[46px]'></div>
                    {children}
                </main>
            </body>
        </html>
    )
}
