import { Roboto_Mono } from 'next/font/google'
import NavBar from '../components/navbar'
import './globals.css'

const openSans = Roboto_Mono({
    subsets: ['latin']
})

export const metadata = {
    title: 'Majestic Food',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={openSans.className}>
                <NavBar />
                {children}
            </body>
        </html>
    )
}
